name: Deploy Frontend
on:
  push:
    branches:
      - develop
      - feat/cicd
  pull_request:
    branches:
      - develop
      - feat/cicd
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ubuntu
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd ~/GSMC-Client-V4
            git pull origin develop
            sudo docker compose down
            sudo docker compose up -d --build